#!/bin/sh

sudo apt-get install libjson0 libjson0-dev libxml2-dev 

VER=2.1.1

wget http://download.osgeo.org/postgis/source/postgis-$VER.tar.gz
tar -xvzf postgis-$VER.tar.gz
cd postgis-VER
sudo ./configure
sudo ./make
sudo make install
cd ..

sudo rm -rf postgis-$VER
sudo rm postgis-$VER.tar.gz

sudo ln -sf /usr/share/postgresql-common/pg_wrapper /usr/local/bin/shp2pgsql
sudo ln -sf /usr/share/postgresql-common/pg_wrapper /usr/local/bin/pgsql2shp
sudo ln -sf /usr/share/postgresql-common/pg_wrapper /usr/local/bin/raster2pgsql
